version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - cat ~/secret.txt | docker login --username nikolajo --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t my-cd-image .
      - docker tag my-cd-image nikolajo/my-cd-image
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push nikolajo/my-cd-image      
artifacts:
    files: myimagefile.json